const $=id=>document.getElementById(id);
let files=[],busy=false,last='',ready=false;
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
async function api(url,options){const r=await fetch(url,options);const b=await r.json();if(!r.ok)throw Error(b.error||'操作失败');return b;}
function notice(text,error=false){$('training-notice').textContent=text;$('training-notice').classList.toggle('error',error);}
function renderFiles(){$('selected-files').replaceChildren();files.forEach((f,i)=>{const row=el('div',undefined,'file'),remove=el('button','移除');remove.type='button';remove.disabled=busy;remove.onclick=()=>{files.splice(i,1);renderFiles();};row.append(el('span',f.name+' · '+(f.size/1024**2).toFixed(1)+' MB'),remove);$('selected-files').append(row);});}
function addFiles(list){if(busy)return;const next=[...files,...list];if(next.length>20){notice('最多选择 20 个音频文件',true);return;}if(next.some(f=>!/\.(wav|mp3|flac|m4a|ogg|webm)$/i.test(f.name))){notice('请选择支持的音频文件',true);return;}if(next.reduce((n,f)=>n+f.size,0)>600*1024**2){notice('文件合计不能超过 600MB',true);return;}files=next;renderFiles();notice('已选择 '+files.length+' 个文件，无需提供配套文字。');}
$('training-audio').onchange=e=>{addFiles([...e.target.files]);e.target.value='';};
const drop=$('audio-drop');drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('training-audio').click();}};drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging');};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');addFiles([...e.dataTransfer.files]);};
$('training-form').onsubmit=async e=>{e.preventDefault();if(busy||!ready)return;if(!files.length){notice('先拖入至少一段录音',true);return;}busy=true;$('start-training').disabled=true;$('training-audio').disabled=true;renderFiles();try{const name=$('training-name').value.trim(),language=$('training-language').value;if(!name)throw Error('请填写音色名称');const inputs=[];for(const [i,f] of files.entries()){notice('正在上传 '+(i+1)+' / '+files.length+'：'+f.name);inputs.push((await api('/api/upload?name='+encodeURIComponent(f.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:f})).id);}await api('/api/trainings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,language,inputs})});files=[];notice('已加入训练队列。你可以离开页面，保持后端运行即可。');await refresh();}catch(e){notice(e.message,true);}finally{busy=false;$('start-training').disabled=!ready;$('training-audio').disabled=false;renderFiles();}};
async function refresh(){try{const data=await api('/api/trainings');const wasReady=ready;ready=data.ready;$('start-training').disabled=busy||!ready;if(!ready)notice(data.error||'训练环境尚未准备完成',true);else if(!wasReady&&!busy)notice('本地训练已就绪 · 与配音依次使用显卡');const sig=JSON.stringify(data.jobs);if(sig===last)return;last=sig;$('training-count').textContent=String(data.jobs.length).padStart(2,'0');$('training-jobs').replaceChildren();if(!data.jobs.length)$('training-jobs').append(el('p','还没有训练任务。放入录音，制作第一个音色。','hint'));for(const j of data.jobs){const row=el('article',undefined,'training-job');row.dataset.id=j.id;const info=el('div'),active=['queued','running','cancelling'].includes(j.status);info.append(el('h3',j.voiceName),el('p',j.error||j.message,j.status==='failed'?'error':'stage'+(active?' busy':'')),el('p',new Date(j.createdAt).toLocaleString('zh-CN')+(j.clips?' · '+j.clips+' 段人声':'')+(j.seconds?' · '+j.seconds+' 秒录音':'')));const actions=el('div',undefined,'actions');if(j.status==='done'){for(const [kind,text] of [['zip','完整音色包 ↓'],['pth','.pth ↓'],['ckpt','.ckpt ↓']]){const a=el('a',text);a.href='/api/trainings/'+j.id+'/'+kind;a.download='';actions.append(a);}const use=el('a','去配音 ↗');use.href='/';use.onclick=()=>localStorage.setItem('voice-workshop-voice',j.voiceId);actions.append(use);}if(active){const cancel=el('button',j.status==='cancelling'?'正在停止…':'取消训练');cancel.disabled=j.status==='cancelling';cancel.onclick=async()=>{cancel.disabled=true;try{await api('/api/trainings/'+j.id+'/cancel',{method:'POST'});await refresh();}catch(e){notice(e.message,true);cancel.disabled=false;}};actions.append(cancel);}if(j.startedAt){const log=el('a','日志 ↗');log.href='/logs/'+j.id+'.log';log.target='_blank';log.rel='noopener';actions.append(log);}row.append(info,actions);$('training-jobs').append(row);}}catch(e){ready=false;$('start-training').disabled=true;notice('连接训练服务失败：'+e.message,true);}}
await refresh();setInterval(refresh,3000);
